// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/common/app-icon/index.vue')['default']
    Button: typeof import('./src/components/common/form/button/index.vue')['default']
    Comment: typeof import('./src/components/comment/index.vue')['default']
    Content: typeof import('./src/components/post/show/content/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Inedx: typeof import('./src/components/post/list/item/inedx.vue')['default']
    Info: typeof import('./src/components/user/info/index.vue')['default']
    Input: typeof import('./src/components/common/form/input/index.vue')['default']
    Item: typeof import('./src/components/comment/list/item/index.vue')['default']
    List: typeof import('./src/components/comment/list/index.vue')['default']
    Menu: typeof import('./src/components/navBar/menu/index.vue')['default']
    NavBar: typeof import('./src/components/navBar/index.vue')['default']
    Navigator: typeof import('./src/components/post/navigator/index.vue')['default']
    Operation: typeof import('./src/components/comment/operation/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Show: typeof import('./src/components/comment/show/index.vue')['default']
    Tag: typeof import('./src/components/post/tag/index.vue')['default']
    Textarea: typeof import('./src/components/common/form/textarea/index.vue')['default']
  }
}

export {}
